# Database Configuration
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://db:3306/bookstore?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
db.username=root
db.password=root123
